sample_file: samples.txt
reference: /work2/genphyse/dynagen/tfaraut/CNVPipeline/work/vargoats/data/Capra_hircus_chr.fa
inputvcf: /work2/genphyse/dynagen/tfaraut/CNVPipeline/work/vargoats/frch-saa/pargenotyping/indel19_frenchbreeds.vcf.gz
statregion: "1:24000000-26000000"
workdir: "genotypes"
